networks:
    ncfs-mc-net:

volumes:
    mc-data:

services:
    ncfs:
        image: barbarbar338/ncfs:buildx-latest 
        container_name: ncfs
        restart: unless-stopped
        depends_on:
            - mc
        ports:
            - 4040:4040
        networks:
            - ncfs-mc-net
        environment:
            NGROK_TCP_PORT: 25565
            NGROK_AUTH_TOKEN: <Your NGROK auth token here>
            CLOUDFLARE_AUTH_EMAIL: <Your Cloudflare email here>
            CLOUDFLARE_API_KEY: <Your Cloudflare Global API key here>
            CLOUDFLARE_ZONE_ID: <Your domain's Cloudflare Zone ID here>
            CLOUDFLARE_CNAME_RECORD_NAME: server.example.com
            CLOUDFLARE_SRV_RECORD: _minecraft._tcp.example.com
            DOCKER_NETWORK: mc

    mc:
        image: itzg/minecraft-server
        container_name: mc
        restart: unless-stopped
        ports:
            - 25565:25565/tcp
        volumes:
            - mc-data:/data
        networks:
            - ncfs-mc-net
        environment:
            EULA: "true"
            TYPE: PAPER
